---
app:
  name: OpenDAX
  domain: app.local
  subdomain: www
render_protect: false
csrfEnabled: false
ssl:
  enabled: false
  email: support@example.com
images:
  peatio: kidodax/peatio-fix:f1
  barong: kidodax/barong-fix:f1
  frontend: kidodax/new-ui-mobile:t5
  tower: quay.io/openware/tower:2.4.5
finex:
  enabled: false
  image: quay.io/openware/finex:2.5.4
vendor:
  frontend: git@github.com:openware/baseapp.git
vault:
  token: changeme
database:
  host: db
  port: 3306
  user: root
  password: changeme
storage:
  provider: Google
  bucketName: opendax-barong-docs-bucket
  region: fra1
  endpoint: https://fra1.digitaloceanspaces.com
  accessKey: changeme
  secretKey: changeme
  signatureVersion: '2'
twilio:
  enabled: false
  phone_number: "+15005550000"
  account_sid: changeme
  auth_token: changeme
gaTrackerKey: ''
captcha:
  type: none
  siteKey: changeme
  secretKey: changeme
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: changeme
  sender_email: noreply@barong.io
  sender_name: Postmaster
  sender_logo: https://storage.googleapis.com/public_peatio/logo.png
wallets:
  eth:
  - kind: deposit
    address: changeme
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: changeme
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: changeme
    max_balance: 1000.0
    secret: changeme
  btc:
  - kind: deposit
    address: changeme
    max_balance: 0.0
  - kind: hot
    address: changeme
    max_balance: 100.0
  - kind: warm
    address: changeme
    max_balance: 1000.0
parity:
  network: testnet
  address: parity
  rpcport: 8545
  port: 30303
bitcoind:
  enabled: false
  rpcuser: admin
  rpcpassword: changeme
  address: bitcoind
  network: testnet
  rpcport: 18332
  port: 18333
litecoind:
  rpcuser: admin
  rpcpassword: changeme
  address: litecoind
  network: testnet
  rpcport: 19332
  port: 19335
terraform:
  credentials: "~/safe/opendax.json"
  project: example-opendax
  region: europe-west4
  zone: europe-west4-a
  instance_name: opendax-cloud
  machine_type: n1-standard-4
  image: debian-cloud/debian-9
